### ISSUE TITLE
Issue with normalizecounts:  non-compatible count matrices

### ISSUE THREAD

**Issue by guruprasada** [lamortenera/epicseg#11]
I have a set of histone marks that need to be normalized. So I ran getcounts on each mark separately to generate a count matrix, and tried to normalize all of the count matrices together using normalizecounts, but ended up with this error:

##############
normalizing matrices
Error in validateCList(clist) : non-compatible count matrices
Calls: <Anonymous> -> <Anonymous> -> normalizecounts -> validateCList
Execution halted
###############

**Comment by lamortenera** [comment]
we clarified by private correspondence why that happened: the count matrices were indeed not compatible. Each matrix should have the same set of column names (aka histone marks). This has also been clarified in the docs.
