### ISSUE TITLE
number of row in save_rdata

### ISSUE THREAD

**Issue by apastore** [lamortenera/epicseg#14]
Hi Alessandro, 
I was trying to generate a granges or annotate the State from save_rdata with bin position (chr, start, end), but I have seen that the Grange has much less bin than the states and posteriors. Would not be nice to have the grange compatible with the other data frame?

thanks!

> dim(rdata$states)
[1] 14548372       10
> dim(rdata$posteriors)
[1]        5 14548372       10
> rdata$segments
GRangesList object of length 10:
$cd20 
GRanges object with 4009875 ranges and 0 metadata columns:
    seqnames               ranges strand
       <Rle>            <IRanges>  <Rle>
  3     chr1       [  201,   600]      *
  4     chr1       [  601, 58000]      *
  5     chr1       [58001, 59000]      *
  4     chr1       [59001, 61400]      *
  5     chr1       [61401, 63000]      *
  .      ...                  ...    ...
  5     chrY [59031601, 59032200]      *
  3     chrY [59032201, 59032400]      *
  4     chrY [59032401, 59361200]      *
  3     chrY [59362801, 59363200]      *
  4     chrY [59363201, 59373400]      *

...
<9 more elements>
-------
seqinfo: 24 sequences from an unspecified genome; no seqlengths

**Comment by lamortenera** [comment]
Hi apastore, 
that's correct, EpiCSeg distinguishes between 3 types of regions:
1. regions before binning (could represent whole chromosomes): GRanges object / bed file
2. bins (have all equal lengths, each region is composed by a certain number of bins): implicitly defined by the regions and a bin size. The posteriors and count matrices are arrays with a dimension representing all bins.
3. segments (continuous bins with the same state): GRanges object / bed file, suitable for being used in genome browser.

I am not exactly sure what you are trying to achieve. The segments object has already the state annotated as name (the first column in the data you pasted here).

**Comment by apastore** [comment]
Hi Alessandro, basically what I need are all the probability for each state (not only the max state) for each cell type over reduced segments. Merging/collapsing the total bin number to cell type common segment (basically removing duplicate state rows)

I have posted a question on stackoverflow:
http://stackoverflow.com/questions/39401376/aggregate-bins-in-large-granges-efficiently

And I have to test the alternative solution (mine was to slow)

Thanks!

**Comment by lamortenera** [comment]
Well let's continue this conversation on stackoverflow then
