### ISSUE TITLE
error running getcounts

### ISSUE THREAD

**Issue by anu-bioinfo** [lamortenera/epicseg#15]
Hey,
I am using epicseg to perform chromatin state segmentation. I get the following error while running getcounts function.

getting counts
Processing 
CoMu_Ct_H3K4me3_B_1.GALv2.20150527.bam: tHaT'S tHa fAStEsT pIlE-uP bAm iN tHe SoUth!!!
Processing 
CoMu_Ct_H3K36me3_B_1.GALv2.20150527.bam: yOu cAn'T pIlE-Up FaStEr!!!
Processing 
CoMu_Ct_H3K9me3_B_1.GALv2.20150527.bam: I gEt gOoSeBuMPs wHen I seE yOu pilEuPpiNg...
Processing 
CoMu_Ct_H3K4me1_B_1.GALv2.20150527.bam: yOu cAn'T pIlE-Up FaStEr!!!
Processing 
CoMu_Ct_H3K27me3_B_1.GALv2.20150527.bam: yOu cAn'T pIlE-Up FaStEr!!!
Processing 
CoMu_UC_H3K27ac_B_1.GALv2.20150527.bam: I gEt gOoSeBuMPs wHen I seE yOu pilEuPpiNg...
pileup done, storing everything in a matrix

Error in t(bindCols(countsList, nthreads = nthreads)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': Error in eval(substitute(expr), envir, enclos) : 
  not compatible with requested type
Calls: bindCols -> .Call
Calls: <Anonymous> -> <Anonymous> -> getcounts -> t
Execution halted

I am running epicseg on R-3.2 and using the following command line parameters:

/ifs/data/nfs_share/sukmb349/work_F0_sukmb349/sukmb349/52_chrom_marks_bam_files/epicseg.R getcounts --mark H3K4me3:CoMu_Ct_H3K4me3_B_1.GALv2.20150527.bam \
                    --mark H3K36me3:CoMu_Ct_H3K36me3_B_1.GALv2.20150527.bam \
                    --mark H3K9me3:CoMu_Ct_H3K9me3_B_1.GALv2.20150527.bam \
                    --mark H3K4me1:CoMu_Ct_H3K4me1_B_1.GALv2.20150527.bam \
                    --mark H3K27me3:CoMu_Ct_H3K27me3_B_1.GALv2.20150527.bam \
                    --mark H3K27ac:/CoMu_UC_H3K27ac_B_1.GALv2.20150527.bam \
                    --regions CoMu_Ct_Input_B_1.bed --mapq 20 --target CoMu_Ct_counts --pairedend TRUE

I am using the  ChIP-Seq "Input"  file for "regions"  parameter. 
Can you please help me out here ? Thanks in advance.

**Comment by lamortenera** [comment]
I take it that you have figured out the problem, so I'll close this issue.

Cheers,
Alessandro
