### ISSUE TITLE
Installation issue on R-3.3.1 and Bioconductor 3.4

### ISSUE THREAD

**Issue by kilpert** [lamortenera/epicseg#16]
Unfortunately, I am unable to get a running installation. The error is (fresh install): 

```
$ Rscript epicseg.R getcounts
loading epicseg
Error in value[[3L]](cond) : 
  the default argument for option binsize causes an error
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

Update: With Bioconductor 3.3 it works.

**Comment by lamortenera** [comment]
hi klimpert,

I just wanted to let you know that I didn't forget about this issue, I just
didn't find the time yet to look at it. It must be related to the new
version of R or Bioconductor. Hopefully I can look at it on Monday or on
Tuesday afternoon.

Cheers
Alessandro

**Comment by lamortenera** [comment]
Hi klipert,

sorry for the long wait. The issue should be fixed now, see commit:
https://github.com/lamortenera/epicseg/commit/3b778cb4b6a2f2d285cdb928a07a72a29d6d6799

Cheers
Alessandro

**Comment by lamortenera** [comment]
The above mentioned commit was now extensively tested and it works.
