### ISSUE TITLE
Legend overlaps figures in report

### ISSUE THREAD

**Issue by mpi-pebert** [lamortenera/epicseg#3]
If a model is trained with a large number of states, the legend overlaps a significant portion of the image in the report (see example)

![overlap](https://cloud.githubusercontent.com/assets/5285064/8820247/05e42b66-3054-11e5-958e-08a8d8946be9.png)

**Comment by lamortenera** [comment]
...and after ONLY 3 months from the day when you posted this issue.... (drum roll)...  the issue is fixed!!! (I hope). Now the legend is on the left margin.
