### ISSUE TITLE
Getting an error during the installation process

### ISSUE THREAD

**Issue by PFRoux** [lamortenera/epicseg#5]
Dear Ale,

Following the instructions from the GitHub manual for the installation of EpicSeq on a cluster running on RedHat, I am having an issue when it comes to download and install the epicseq GitHub repository.

<img width="1128" alt="capture d ecran 2015-07-31 a 10 45 55" src="https://cloud.githubusercontent.com/assets/12641881/9003791/5df31bf4-3771-11e5-83ea-24d630008d3a.png">

Do you know why this problem is occurring ?

Best,

Pierre-François

**Comment by lamortenera** [comment]
Dear Pierre-François,
it looks like your compiler is not fully supporting the C++11 standard. 
The flag that you see while installing the package: 

    g++ -std=c++0x ....

should be

    g++ -std=c++11 ....

Which version of the g++ compiler are you using? If it is not too old, you might be able to fix this by doing the following:

1. create an empty text file HOME/.R/Makevars , where HOME is your home directory. If the folder .R doesn't exist, create it.
2. add the following line: 

        CXX1XSTD=-std=c++11

Save everything and try installing again. Let me know if it works, and if it doesn't, let me know your g++ version. 
Also, the following ![link](https://cran.r-project.org/doc/manuals/R-admin.html#Customizing-package-compilation)  has some information about setting the right flags during compilation.

Best,
Ale

**Comment by Hashem72** [comment]
I have the same problem and the above mentioned solution didnt solve it! My 4.4.6

**Comment by lamortenera** [comment]
Reading the ![following website](https://gcc.gnu.org/projects/cxx0x.html)  it seems that the first gcc version fully supporting the c++11 standard is 4.7, so Hashem, your version is probably too old. 

Could you please try the following solution and let me know if it works?
1. download and install a recent gcc compiler (>= 4.7, preferably 4.8). The executable will have a path, for instance `/path/to/compiler/gcc`.
2. In you personal Makevars file (the one in HOME/.R/Makevars , where HOME is your home directory), set the following flags:

        CXX1X=/path/to/compiler/gcc
        CXX1XSTD=-std=c++11

Lastly, I know that it might seem unnecessary to you, but I would really value your feedback, even if everything went fine and there is nothing to say. So please post here how it went.

Good luck,
Alessandro

**Comment by simjbaum** [comment]
I had the same error as mentioned in the comments and applied your solution.
It worked. Now I am curious to test EpicSeg :-) .

Thanks and best wishes,
Simon

**Comment by Hashem72** [comment]
Hi Ale,
Thanks for your suggestion and sorry for the late reply.
I followed your suggestion with our newly installed gcc5.2.0. It passed the previous error but eventually failed with the following error:
*****************************
Creating a generic function for ‘nchar’ from package ‘base’ in package ‘S4Vectors’
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/bi/home/koohyh/R/x86_64-unknown-linux-gnu-library/3.2/epicseg/libs/epicseg.so':
  /usr/lib64/libgomp.so.1: version `GOMP_4.0' not found (required by /bi/home/koohyh/R/x86_64-unknown-linux-gnu-library/3.2/epicseg/libs/epicseg.so)
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/bi/home/koohyh/R/x86_64-unknown-linux-gnu-library/3.2/epicseg’
Error: Command failed (1)
****************************
Again I will appreciate your any  point to this.
thansk
H

**Comment by s-andrews** [comment]
I've tried this install (I'm working with Hashem), and have got a bit further but eventually the install fails with a missing symbol which looks like a problem with libstdc++, but when I try the same thing manually (rather than by using devtools) I can't reproduce the failure.  My notes are at:

http://www.bioinformatics.babraham.ac.uk/cgi-bin/helpdeskuser.cgi?action=show_job&public_id=slurpbrae

..and suggestions as to what I'm missing would be appreciated.  I suspect it's something pretty trivial at this point.

**Comment by lamortenera** [comment]
Dear Simon and Hashem,
I am extremely sorry that setting up EpiCSeg is causing you such an headache. It might be harder than I thought to switch compiler once R is already installed. The compiler and load flags used by R are all controlled using the `~/.R/Makevars` file. 
Some of them are listed here:  
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-Makevars
others are listed here:
https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Compile-and-load-flags  
You can check which value these flags will get when you compile a package with R. For instance, to see if the flag `CXX1X` is set correctly, you can type at the command line:

    R CMD config CXX1X

To be honest I don't fully understand how each flag works, but in your case, I would try to use the following `~/.R/Makevars` file:

    CXX1X=/bi/apps/gcc/5.2.0/bin/gcc
    CXX1XSTD=-std=c++11 
    LDFLAGS:=-L/usr/lib64/openmpi/lib/ -L/bi/apps/gcc/5.2.0/lib64/ $(LDFLAGS)

If this still does not work and you are tired of trying to understand what R does to compile packages, I would reinstall R using the newest gcc.

Let me know how it goes! and sorry for these problems!

**Comment by s-andrews** [comment]
I've spent a while longer on this.  I tried modifying the Makevars file with the extra LD flags, but with no change.  I even re-compiled R with the new gcc and got the same error.

I then went back to the manual compilation I did of the github code and added some flags to check the objects for invalid symbols and found that when I do this I do get errors, even when compiling outside of the R environment and I see the same types of missing symbols as reported within R.  I'm hoping this is just a missing include somewhere (maybe one which used to be default, but isn't in the latest gcc?).

There are tons of errors, but I suspect the first few will point you in the right direction.  All of the earlier gcc commands to create the individual object files work OK, but the final command to build the epicseg.so file is the one which generates errors:

/bi/apps/gcc/5.2.0/bin/gcc -std=c++11 -shared -L/bi/apps/R/3.2.1/lib64/R/lib -L/usr/local/lib64 -o epicseg.so RcppExports.o misc.o normalization.o segments.o -fopenmp -L/bi/apps/R/3.2.1/lib64/R/lib -lR -Wl,-z,defs

/bi/apps/gcc/5.2.0/include/c++/5.2.0/ext/new_allocator.h:110: undefined reference to `operator delete(void*)'
segments.o: In function `deallocate':
/bi/apps/gcc/5.2.0/include/c++/5.2.0/ext/new_allocator.h:110: undefined reference to `operator delete(void*)'
segments.o: In function `_M_allocate':
/bi/apps/gcc/5.2.0/include/c++/5.2.0/ext/new_allocator.h:104: undefined reference to `operator new(unsigned long)'
segments.o: In function `__destroy<Segment*>':
/bi/apps/gcc/5.2.0/include/c++/5.2.0/ext/new_allocator.h:110: undefined reference to `operator delete(void*)'
segments.o: In function `void std::vector<Segment, std::allocator<Segment> >::_M_emplace_back_aux<Segment>(Segment&&)':
/bi/apps/gcc/5.2.0/include/c++/5.2.0/ext/new_allocator.h:110: undefined reference to `operator delete(void*)'
segments.o: In function `__static_initialization_and_destruction_0':
/bi/apps/gcc/5.2.0/include/c++/5.2.0/iostream:74: undefined reference to `std::ios_base::Init::Init()'
/bi/apps/gcc/5.2.0/include/c++/5.2.0/iostream:74: undefined reference to `std::ios_base::Init::~Init()'
segments.o: In function `basic_ios':
/bi/apps/gcc/5.2.0/include/c++/5.2.0/bits/basic_ios.h:462: undefined reference to `std::ios_base::ios_base()'
/bi/apps/gcc/5.2.0/include/c++/5.2.0/bits/basic_ios.h:462: undefined reference to `vtable for std::basic_ios<char, std::char_traits<char> >'
segments.o: In function `Rostream':
/bi/apps/R/3.2.1/lib64/R/library/Rcpp/include/Rcpp/iostream/Rstreambuf.h:50: undefined reference to `operator new(unsigned long)'
segments.o: In function `basic_streambuf':
/bi/apps/gcc/5.2.0/include/c++/5.2.0/streambuf:466: undefined reference to `vtable for std::basic_streambuf<char, std::char_traits<char> >'
/bi/apps/gcc/5.2.0/include/c++/5.2.0/streambuf:466: undefined reference to `std::locale::locale()'
segments.o: In function `basic_ostream':
/bi/apps/gcc/5.2.0/include/c++/5.2.0/ostream:85: undefined reference to `std::basic_ios<char, std::char_traits<char> >::init(std::basic_streambuf<char, std::char_traits<char> >*)'
segments.o: In function `basic_ios':
/bi/apps/gcc/5.2.0/include/c++/5.2.0/bits/basic_ios.h:462: undefined reference to `std::ios_base::ios_base()'
segments.o: In function `Rostream':
/bi/apps/R/3.2.1/lib64/R/library/Rcpp/include/Rcpp/iostream/Rstreambuf.h:50: undefined reference to `operator new(unsigned long)'
segments.o: In function `Rstreambuf':
/bi/apps/gcc/5.2.0/include/c++/5.2.0/streambuf:466: undefined reference to `std::locale::locale()'
segments.o: In function `basic_ostream':
/bi/apps/gcc/5.2.0/include/c++/5.2.0/ostream:85: undefined reference to `std::basic_ios<char, std::char_traits<char> >::init(std::basic_streambuf<char, std::char_traits<char> >*)'
segments.o: In function `__static_initialization_and_destruction_0':
/bi/apps/gcc/5.2.0/include/c++/5.2.0/bits/basic_ios.h:282: undefined reference to `std::ios_base::~ios_base()'
/bi/apps/gcc/5.2.0/include/c++/5.2.0/bits/basic_ios.h:282: undefined reference to `std::ios_base::~ios_base()'
segments.o:(.data.rel.ro._ZTIN4Rcpp6not_s4E[_ZTIN4Rcpp6not_s4E]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
segments.o:(.data.rel.ro._ZTIN4Rcpp6not_s4E[_ZTIN4Rcpp6not_s4E]+0x10): undefined reference to `typeinfo for std::exception'
segments.o:(.data.rel.ro._ZTIN4Rcpp12no_such_slotE[_ZTIN4Rcpp12no_such_slotE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
segments.o:(.data.rel.ro._ZTIN4Rcpp12no_such_slotE[_ZTIN4Rcpp12no_such_slotE]+0x10): undefined reference to `typeinfo for std::exception'
collect2: error: ld returned 1 exit status

**Comment by lamortenera** [comment]
I think I know what the problem could be. These symbols that it cannot find all belong to the standard c++ library. You should compile with g++, not with gcc. 
The suggestion to write: 

     CXX1X=/bi/apps/gcc/5.2.0/bin/gcc

was probably a bad one. Is there also the g++ binary in that folder? can you just write:

     CXX1X=/bi/apps/gcc/5.2.0/bin/g++

? Or maybe you have to install a fresh g++. If that still doesn't work, we will try this: I build a binary version of EpiCSeg in my platform and we see if you can use that right-away, without compilation. You are using a x86_64 platform right?

**Comment by s-andrews** [comment]
Yes! That was it.  I can now compile and install the module and it loads and runs a basic test OK afterwards.

For the record the full solution was:

1) Install the latest gcc (5.2.0 when I did it).  In my case it was to /bi/apps/gcc/5.2.0

2) Edit (or create) ~/.R/Makevars to add the lines:

CXX1X=/bi/apps/gcc/5.2.0/bin/g++
CXX1XSTD=-std=c++11

3) Change LD_LIBRARY_PATH to contain the include directory for the new gcc:

export LD_LIBRARY_PATH=/bi/apps/gcc/5.2.0/lib64

Then follow the epicseg install instructions in Readme.md

Thanks for your help getting this working.

**Comment by lamortenera** [comment]
I am very happy that we made it :D Just to make sure we understood everything, are you sure that it is necessary to set the LD_LIBRARY_PATH ? it doesn't work otherwise?

**Comment by s-andrews** [comment]
Yes, you need that otherwise it fails with an error about the LIBGOMP
version.  I think that¹s nothing to do with your code, but just from using
the new gcc - you need to put the lib64 from that gcc into the LD path as
well.

Simon.

From:  lamortenera <notifications@github.com>
Reply-To:  lamortenera/epicseg
<reply+007c7ae3728ec545fe9211af4c1a74a5913c1d5297c4112592cf000000011206a96e9
2a169ce05dc9e5c@reply.github.com>
Date:  Tuesday, 8 September 2015 14:49
To:  lamortenera/epicseg <epicseg@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>
Subject:  Re: [epicseg] Getting an error during the installation process
(#5)


I am very happy that we made it :D Just to make sure we understood
everything, are you sure that it is necessary to set the LD_LIBRARY_PATH ?
it doesn't work otherwise?


Reply to this email directly or view it on GitHub
<https://github.com/lamortenera/epicseg/issues/5#issuecomment-138565408> .

**Comment by lamortenera** [comment]
Thanks so much, so I am going to name this issue: compiling EpiCSeg with a new compiler.
