### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by wcstcyx** [lamortenera/epicseg#6]
I have read your paper about EpiCSeg and want to use it. When I install epicseg, I have encountered a problem. My environment is 64 bit Windows 7, R x64 3.2.2.

> devtools::install_github("lamortenera/kfoots")

Downloading GitHub repo lamortenera/kfoots@master
Installing kfoots
"D:/PROGRA~2/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  "C:/Users/WangCan/AppData/Local/Temp/RtmpsPx7fW/devtoolsd05448db330d/lamortenera-kfoots-d3f5846"  \
  --library="D:/Program Files/R/R-3.2.2/library" --install-tests 

* installing *source* package 'kfoots' ...
** libs

*** arch - i386
g++ -m32 -std=c++0x -I"D:/PROGRA~2/R/R-32~1.2/include" -DNDEBUG    -I"D:/Program Files/R/R-3.2.2/library/Rcpp/include" -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
g++ -m32 -std=c++0x -I"D:/PROGRA~2/R/R-32~1.2/include" -DNDEBUG    -I"D:/Program Files/R/R-3.2.2/library/Rcpp/include" -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c hmmfoots_methods.cpp -o hmmfoots_methods.o
**hmmfoots_methods.cpp:2:20: fatal error: core.cpp: No such file or directory**
compilation terminated.
make: *** [hmmfoots_methods.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "D:/PROGRA~2/R/R-32~1.2/etc/i386/Makeconf" -f "D:/PROGRA~2/R/R-32~1.2/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="kfoots.dll" OBJECTS="RcppExports.o hmmfoots_methods.o init.o kfoots_methods.o schedule.o"' had status 2
ERROR: compilation failed for package 'kfoots'
* removing 'D:/Program Files/R/R-3.2.2/library/kfoots'
Error: Command failed (1)

**In your kfoots/src/hmmfoots_methods.cpp, I find #include "core.cpp". You use quoted form, but "core.cpp" is in kfoots/inst/include/ and can not be found under kfoots/src/. So maybe it can not be found by compiler.**

Would you please solve this problem and I hope to use epicseg as soon as possible.

Thank you!

**Comment by lamortenera** [comment]
Dear wcstcyx,
it is not uncommon that R packages have problems on windows. I will look into that right now and let you know as soon as possible

**Comment by wcstcyx** [comment]
Thank you!

**Comment by lamortenera** [comment]
Dear wcstcyx,
I removed some issues with the kfoots package and I tried it on a windows workstation. It worked! 
However, you probably won't have support for multiple threads. If this is the case you will also see a lot of compiler warnings during installation, but you can safely ignore them.
I am curious to know if it works also for you now.
Just redo:

    devtools::install_github("lamortenera/kfoots")
    devtools::install_github("lamortenera/epicseg")

Good luck!

**Comment by wcstcyx** [comment]
Hi Ale,

I have installed EpiCSeg successfully! Thank you very much!

Can
