### ISSUE TITLE
Correction for input

### ISSUE THREAD

**Issue by fwere** [lamortenera/epicseg#9]
Hi,

Is there a way to correct for input when generating the counts matrices for the histone marks?

Thank you.

Felipe

**Comment by lamortenera** [comment]
Hi Felipe,

to take the input levels into account in EpiCSeg, you can add an Input experiment as if it was another histone mark. In fact EpiCSeg model gives a lot of importance to the relative abundances between histone marks, so if both your input and your histone marks are high for some genomic bins, this would be considered "normal" by EpiCSeg's probability model.

There is no built-in way of correcting for input by altering the counts you get from a BAM file.

Cheers,
Alessandro

**Comment by fwere** [comment]
Hi Alessandro,

Thank you for the information. 
So if both the input and the histone marks are high for some genomic bins, these bins would probably be assigned a "low signal" state by EpiCSeg?

**Comment by lamortenera** [comment]
It's hard to say with confidence what will happen. Bins with high counts
are usually related to "active states", such as promoter states.
The Input won't be used to change the fact that there are high counts, it
will be used to add evidence to the fact that all counts are high.

**Comment by fwere** [comment]
Ok, thank you very much for the information!!

Best

**Comment by fwere** [comment]
Hi Alessandro,

I would like to ask you what are the memory requirements of EpiCSeg.
I had to run the segment command of EpiCSeg in a computer cluster because it took up more than 40Gb of virtual memory when I processed a single sample.
Now I am trying to generate a model for 15 samples (corresponding to 5 different cell types, 3 samples each), but the nodes of my computer cluster seem to be unable to process the segment command, no matter how many threads I use.

Is there a way I can control memory usage when running EpiCSeg (I tried the ulimit command but it didn't work)?

Thank you!

Best,

Felipe

P.S. Should I post a ticket about this issue in GitHub?

________________________________
De: lamortenera [notifications@github.com]
Enviado: jueves, 31 de marzo de 2016 12:13
Para: lamortenera/epicseg
CC: Nicolau.Filipe
Asunto: Re: [lamortenera/epicseg] Correction for input (#9)


Hi Felipe,

to take the input levels into account in EpiCSeg, you can add an Input experiment as if it was another histone mark. In fact EpiCSeg model gives a lot of importance to the relative abundances between histone marks, so if both your input and your histone marks are high for some genomic bins, this would be considered "normal" by EpiCSeg's probability model.

There is no built-in way of correcting for input by altering the counts you get from a BAM file.

Cheers,
Alessandro

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/lamortenera/epicseg/issues/9#issuecomment-203864955>


**NOTA DE CONFIDENCIALIDAD** Este correo electrónico, y en su caso los ficheros adjuntos, pueden contener información protegida para el uso exclusivo de su destinatario. Se prohíbe la distribución, reproducción o cualquier otro tipo de transmisión por parte de otra persona que no sea el destinatario. Si usted recibe por error este correo, se ruega comunicarlo al remitente y borrar el mensaje recibido.

**CONFIDENTIALITY NOTICE** This email communication and any attachments may contain confidential and privileged information for the sole use of the designated recipient named above. Distribution, reproduction or any other use of this transmission by any party other than the intended recipient is prohibited. If you are not the intended recipient please contact the sender and delete all copies.

**Comment by lamortenera** [comment]
Hi Felipe,

it is very surprising that EpiCSeg is requiring 40gb of memory. How many
states are you using by curiosity?
EpiCSeg should use approx  2*nbins*nstates*nstates bytes, so if you have 10
states and 15*(10^6) bins, EpiCSeg should use about 1 Gigabyte.

Cheers,
Alessandro


On Tue, Apr 19, 2016 at 11:59 AM, fwere <notifications@github.com> wrote:

> Hi Alessandro,
>
> I would like to ask you what are the memory requirements of EpiCSeg.
> I had to run the segment command of EpiCSeg in a computer cluster because
> it took up more than 40Gb of virtual memory when I processed a single
> sample.
> Now I am trying to generate a model for 15 samples (corresponding to 5
> different cell types, 3 samples each), but the nodes of my computer cluster
> seem to be unable to process the segment command, no matter how many
> threads I use.
>
> Is there a way I can control memory usage when running EpiCSeg (I tried
> the ulimit command but it didn't work)?
>
> Thank you!
>
> Best,
>
> Felipe
>
> P.S. Should I post a ticket about this issue in GitHub?
>
> ________________________________
> De: lamortenera [notifications@github.com]
> Enviado: jueves, 31 de marzo de 2016 12:13
> Para: lamortenera/epicseg
> CC: Nicolau.Filipe
> Asunto: Re: [lamortenera/epicseg] Correction for input (#9)
>
>
> Hi Felipe,
>
> to take the input levels into account in EpiCSeg, you can add an Input
> experiment as if it was another histone mark. In fact EpiCSeg model gives a
> lot of importance to the relative abundances between histone marks, so if
> both your input and your histone marks are high for some genomic bins, this
> would be considered "normal" by EpiCSeg's probability model.
>
> There is no built-in way of correcting for input by altering the counts
> you get from a BAM file.
>
> Cheers,
> Alessandro
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<
> https://github.com/lamortenera/epicseg/issues/9#issuecomment-203864955>
>
>
> **NOTA DE CONFIDENCIALIDAD** Este correo electrónico, y en su caso los
> ficheros adjuntos, pueden contener información protegida para el uso
> exclusivo de su destinatario. Se prohíbe la distribución, reproducción o
> cualquier otro tipo de transmisión por parte de otra persona que no sea el
> destinatario. Si usted recibe por error este correo, se ruega comunicarlo
> al remitente y borrar el mensaje recibido.
>
> **CONFIDENTIALITY NOTICE** This email communication and any attachments
> may contain confidential and privileged information for the sole use of the
> designated recipient named above. Distribution, reproduction or any other
> use of this transmission by any party other than the intended recipient is
> prohibited. If you are not the intended recipient please contact the sender
> and delete all copies.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/lamortenera/epicseg/issues/9#issuecomment-211860990>
>



-- 
Alessandro Mammana, PhD
Max Planck Institute for Molecular Genetics
Ihnestraße 63-73
D-14195 Berlin, Germany

**Comment by fwere** [comment]
Hi Alessandro,

This is an extract of the top command for the cluster node where epicseg is running.


top - 11:18:35 up 7 days, 19:50,  1 user,  load average: 1.20, 1.29, 1.31
Tasks: 246 total,   2 running, 244 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  3.1 sy,  0.0 ni, 90.8 id,  5.9 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  49453564 total, 49140996 used,   312568 free,      512 buffers
KiB Swap: 70312496 total, 34738096 used, 35574400 free.     4004 cached Mem

  PID     USER          PR      NI        VIRT            RES            SHR     S      %CPU     %MEM     TIME+ COMMAND
24333   fnicolau      20       0         67.550g         0.045t        300        D       5.0             97.9             273:07.22 R



At present, I'm traning a 12 model state, so the amount of memory used according to the formula should be around 1.5 Gb.

In the case of chromHMM the inclusion of 15 samples in the analysis scales up the memory used by almost as much as the number of samples included , shouldn't this be the case for EpicSeg?

This is the command line I'm using:
Rscript epicseg.R segment -c S00FWHH1:./S00FWHH1_input_norm.txt -c S00FXFH1:./S00FXFH1_input_norm.txt -c S00FYDH1:./S00FYDH1_input_norm.txt -c S00G03H1:./S00G03H1_input_norm.txt -c S00G11H1:./S00G11H1_input_norm.txt -c S00G3YH1:./S00G3YH1_input_norm.txt -c S00JE0H1:./S00JE0H1_input_norm.txt -c S00JFZH1:./S00JFZH1_input_norm.txt -c S00JGXH1:./S00JGXH1_input_norm.txt -c S00JHVH1:./S00JHVH1_input_norm.txt -c S00K5EH1:./S00K5EH1_input_norm.txt -c S00K6CH1:./S00K6CH1_input_norm.txt -c S00K7AH1:./S00K7AH1_input_norm.txt -c S00K88H1:./S00K88H1_input_norm.txt -c S00VCUH1:./S00VCUH1_input_norm.txt -c S00VDSH1:./S00VDSH1_input_norm.txt -c S00VEQH1:./S00VEQH1_input_norm.txt -c S00VFOH1:./S00VFOH1_input_norm.txt -r ./S00K88H1_input_refined_regions.bed -n 12 -o ./Results_Neutrophils/Learn_model_12 -p segments_neutrophils_input_12 --save_rdata

Thank you!

Best,

Felipe


________________________________
De: lamortenera [notifications@github.com]
Enviado: martes, 19 de abril de 2016 15:12
Para: lamortenera/epicseg
CC: Nicolau.Filipe
Asunto: Re: [lamortenera/epicseg] Correction for input (#9)

Hi Felipe,

it is very surprising that EpiCSeg is requiring 40gb of memory. How many
states are you using by curiosity?
EpiCSeg should use approx 2*nbins*nstates*nstates bytes, so if you have 10
states and 15*(10^6) bins, EpiCSeg should use about 1 Gigabyte.

Cheers,
Alessandro


On Tue, Apr 19, 2016 at 11:59 AM, fwere <notifications@github.com> wrote:

> Hi Alessandro,
>
> I would like to ask you what are the memory requirements of EpiCSeg.
> I had to run the segment command of EpiCSeg in a computer cluster because
> it took up more than 40Gb of virtual memory when I processed a single
> sample.
> Now I am trying to generate a model for 15 samples (corresponding to 5
> different cell types, 3 samples each), but the nodes of my computer cluster
> seem to be unable to process the segment command, no matter how many
> threads I use.
>
> Is there a way I can control memory usage when running EpiCSeg (I tried
> the ulimit command but it didn't work)?
>
> Thank you!
>
> Best,
>
> Felipe
>
> P.S. Should I post a ticket about this issue in GitHub?
>
> ________________________________
> De: lamortenera [notifications@github.com]
> Enviado: jueves, 31 de marzo de 2016 12:13
> Para: lamortenera/epicseg
> CC: Nicolau.Filipe
> Asunto: Re: [lamortenera/epicseg] Correction for input (#9)
>
>
> Hi Felipe,
>
> to take the input levels into account in EpiCSeg, you can add an Input
> experiment as if it was another histone mark. In fact EpiCSeg model gives a
> lot of importance to the relative abundances between histone marks, so if
> both your input and your histone marks are high for some genomic bins, this
> would be considered "normal" by EpiCSeg's probability model.
>
> There is no built-in way of correcting for input by altering the counts
> you get from a BAM file.
>
> Cheers,
> Alessandro
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<
> https://github.com/lamortenera/epicseg/issues/9#issuecomment-203864955>
>
>
> **NOTA DE CONFIDENCIALIDAD** Este correo electrónico, y en su caso los
> ficheros adjuntos, pueden contener información protegida para el uso
> exclusivo de su destinatario. Se prohíbe la distribución, reproducción o
> cualquier otro tipo de transmisión por parte de otra persona que no sea el
> destinatario. Si usted recibe por error este correo, se ruega comunicarlo
> al remitente y borrar el mensaje recibido.
>
> **CONFIDENTIALITY NOTICE** This email communication and any attachments
> may contain confidential and privileged information for the sole use of the
> designated recipient named above. Distribution, reproduction or any other
> use of this transmission by any party other than the intended recipient is
> prohibited. If you are not the intended recipient please contact the sender
> and delete all copies.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/lamortenera/epicseg/issues/9#issuecomment-211860990>
>



--
Alessandro Mammana, PhD
Max Planck Institute for Molecular Genetics
Ihnestraße 63-73
D-14195 Berlin, Germany

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/lamortenera/epicseg/issues/9#issuecomment-211918724>


**NOTA DE CONFIDENCIALIDAD** Este correo electrónico, y en su caso los ficheros adjuntos, pueden contener información protegida para el uso exclusivo de su destinatario. Se prohíbe la distribución, reproducción o cualquier otro tipo de transmisión por parte de otra persona que no sea el destinatario. Si usted recibe por error este correo, se ruega comunicarlo al remitente y borrar el mensaje recibido.

**CONFIDENTIALITY NOTICE** This email communication and any attachments may contain confidential and privileged information for the sole use of the designated recipient named above. Distribution, reproduction or any other use of this transmission by any party other than the intended recipient is prohibited. If you are not the intended recipient please contact the sender and delete all copies.
